---
version: '2'
services:
  zookeeper:
    userns_mode: "host"
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    userns_mode: "host"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TOOLS_LOG4J_LOGLEVEL: DEBUG

  elasticsearch:
    image: elasticsearch:8.4.1
    userns_mode: "host"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - .:/elasticsearch/data

  backend:
    userns_mode: "host"
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: docker_kafka
    image: kafka/docker_kafka
    depends_on:
      - kafka
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: /bin/bash
    tty: true
    stdin_open: true
